stages:
  split:
    cmd: python src/data/split_data.py config.yaml
    deps:
      - src/data/split_data.py
      - config.yaml
      - https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/data/normalize_data.py config.yaml
    deps:
      - src/data/normalize_data.py
      - config.yaml
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  gridsearch:
    cmd: python src/models/grid_search.py config.yaml
    deps:
      - src/models/grid_search.py
      - config.yaml
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/best_model.pkl

  training:
    cmd: python src/models/train_model.py config.yaml
    deps:
      - src/models/train_model.py
      - config.yaml
      - models/best_model.pkl
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/trained_model.pkl

  evaluate:
    cmd: python src/models/evaluate_model.py config.yaml
    deps:
      - src/models/evaluate_model.py
      - config.yaml
      - models/trained_model.pkl
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
    outs:
      - data/predictions.csv
    metrics:
    - metrics/scores.json:
        cache: false