stages:
  split:
    cmd: python src/data/data_split.py src/params.yaml
    deps:
      - src/data/data_split.py
      - src/params.yaml
      - https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize:
    cmd: python src/data/normalize.py src/params.yaml
    deps:
      - src/data/normalize.py
      - src/params.yaml
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  gridsearch:
    cmd: python src/models/grid_search.py src/params.yaml
    deps:
      - src/models/grid_search.py
      - src/params.yaml
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/best_params.pkl

  training:
    cmd: python src/models/training.py src/params.yaml
    deps:
      - src/models/training.py
      - src/params.yaml
      - models/best_params.pkl
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/gbr_model.pkl

  evaluate:
    cmd: python src/models/evaluate.py src/params.yaml
    deps:
      - src/models/evaluate.py
      - src/params.yaml
      - models/gbr_model.pkl
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
    outs:
      - data/prediction/prediction.csv
    metrics:
    - metrics/scores.json:
        cache: false