split_data:
  data_url: "https://datascientest-mlops.s3.eu-west-1.amazonaws.com/mlops_dvc_fr/raw.csv"
  target_column: "silica_concentrate"
  test_size: 0.2
  random_state: 42
  output_dir: "data/processed"

normalize_data:
  input_dir: "data/processed"
  output_dir: "data/processed"

grid_search:
  input_dir: "data/processed"
  output_dir: "models"
  param_grid:
    n_estimators: [100, 150]
    max_depth: [10, 20, 30]
  random_state: 42

training:
  input_dir: "data/processed"
  output_dir: "models"

evaluate_model:
  input_dir: "data/processed"
  model_dir: "models"
  metrics_dir: "metrics"
  prediction_dir: "data/prediction"